### ISSUE TITLE
CLI (and server) crashes when my client exits

### ISSUE THREAD

**Issue by TheInitializer** [decent-chat/decent#190]
When I close my client program with ^C (or it crashes) the Decent CLI spits out this error and then crashes:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1016:11)
    at TCP.onread (net.js:609:25)
```

**Comment by heyitsmeuralex** [comment]
This is Windows-only - neither @towerofnix nor I can help with this.

**Comment by TheInitializer** [comment]
so it seems that the server is crashing whenever a websocket isn't closed properly.

**Comment by heyitsmeuralex** [comment]
Might be able to fix this by handling `error` events on the socket if we don't already.
